"""
Django settings for backed_project_multilab project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from .jazzmin import JAZZMIN_SETTINGS
from pathlib import Path
import environ
import os
env = environ.Env()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent
environ.Env.read_env(BASE_DIR / '.env')
LOGOUT_REDIRECT_URL = '/'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b_z73j80aa!3h9s+%ui*ii*bl%(cdw*w-tpukpqngcr7+!_dtw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
WHITENOISE_SKIP_MISSING = False
ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=[
                         '102.211.210.120', 'multilab-tunisia.com.tn', 'www.multilab-tunisia.com.tn'])
APPEND_SLASH = False
WHITENOISE_AUTOREFRESH = False  # Enable auto-refresh for development
WHITENOISE_INDEX_FILE = True
CSRF_COOKIE_SECURE = True

# Application definition
APPEND_SLASH = False

INSTALLED_APPS = [
    'jazzmin',


    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account.apps.AccountConfig',
    'rest_framework',
    'corsheaders',
    'admin_honeypot',
    'login_history',
    'multi_lab.apps.MultiLabConfig',  # Changed this line
    'ParametersAnalyse.apps.ParametersanalyseConfig',
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = (
    'https://102.211.210.120',
    'https://multilab-tunisia.com.tn',
    'https://www.multilab-tunisia.com.tn',
    'http://102.211.210.120',
   
)
CSRF_TRUSTED_ORIGINS = [
    'https://102.211.210.120',
    'https://multilab-tunisia.com.tn',
     'https://www.multilab-tunisia.com.tn',
    'http://102.211.210.120',

]
CORS_ALLOWED_ORIGINS = [
    'https://102.211.210.120',
    'https://multilab-tunisia.com.tn',
     'https://www.multilab-tunisia.com.tn',
    'http://102.211.210.120',

]
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'backed_project_multilab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backed_project_multilab.wsgi.application'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'multilab',
        'USER': 'multilab',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
DOMAIN = 'multilab-tunisia.com.tn'
SITE_NAME = 'MULTILAB a.s'
# https://docs.djangoproject.com/en/3.1/topics/i18n/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True
#! login url"""
LOGIN_URL = '/login_view'
USE_TZ = True
# send email config
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'ssl0.ovh.net'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_PORT = 465
EMAIL_USE_TLS = False  # Disable TLS
EMAIL_USE_SSL = True   # Enable SSL

EMAIL_HOST_USER = 'commercial@multilab.com.tn'
EMAIL_HOST_PASSWORD = 'b6htafjo'
DEFAULT_FROM_EMAIL = 'commercial@multilab.com.tn'

# GOOGLE_CLIENT_ID = '84824279187-i984iquv2b83e4gf9b5jort0p770v21g.apps.googleusercontent.com'
# GOOGLE_CLIENT_SECRET = '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'
# SOCIAL_AUTH_PASSWORD = 'efzmefjfeqffsjm'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
     os.path.join(BASE_DIR, '../my-react-app/dist'),

]


AUTH_USER_MODEL = 'account.User'
JAZZMIN_SETTINGS = JAZZMIN_SETTINGS

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django_error.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}