# Generated by Django 4.2 on 2025-01-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysesProduitCosmetique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyses_microbiologiques_produits_cosmetique', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "Ajouter Analyses Microbiologiques des Produits Cosmétique et D'hygiène",
            },
        ),
        migrations.CreateModel(
            name='TypeAnalysesPhysicochimiquesProduitsEaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyses_physicochimiques_produits_eaux', models.CharField(max_length=255, verbose_name='Analyses Physicochimiques des Produits d Eaux ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAzoteKjedahl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_azote_kjedahl', models.CharField(max_length=255, verbose_name='Azote Kjeldahl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDevi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alimentation_animale', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ajouter Analyses de l’alimentation animale',
            },
        ),
        migrations.CreateModel(
            name='TypeDeviAnalyseMicrobiologieProduitsEaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyse_microbiologie_produits_eaux', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDeviAnalysesmicrobiologiquesproduitsalimentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyses_microbiologiques_produits_alimentaires', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ajouter Analyses Microbiologiques des Produits Alimentaires',
            },
        ),
        migrations.CreateModel(
            name='TypeDeviANALYSESPHYSICOCHIMIQUESHUILESETPRODUITSGRAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyses_physicochimiques_huiles_et_produits_gras', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ajouter Analyses Physicochimiques Huiles et Produits Gras',
            },
        ),
        migrations.CreateModel(
            name='TypeDeviANALYSESPHYSICOCHIMIQUESMIEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyses_physicochimiques_miel', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDeviANALYSESPHYSICOCHIMIQUESPRODUITSLAITIERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyses_physicochimiques_produits_laitiers', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ajouter Analyses Physicochimiques des Produits Laitiers',
            },
        ),
        migrations.CreateModel(
            name='TypeDeviANALYSESPHYSICOCHIMIQUESPRODUITSPECHE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyses_physicochimiques_produit_peche', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDeviANALYSESPHYSICOCHIMIQUESVIANDESDERIVES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyses_physicochimiques_viandes_et_derives', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ajouter Analyses Physicochimiques des Viandes et Dérivés',
            },
        ),
        migrations.CreateModel(
            name='TypeDeviBEURRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_beurre', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDeviFROMAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fromage', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
