# Generated by Django 5.0.2 on 2024-05-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParametersAnalyse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedevianalysesmicrobiologiquesproduitsalimentaires',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-06 12:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typedevianalysesphysicochimiquesviandesderives',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
