# Generated by Django 5.0.4 on 2025-01-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParametersAnalyse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysesProduitCosmetique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyses_microbiologiques_produits_cosmetique', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "Ajouter Analyses Microbiologiques des Produits Cosmétique et D'hygiène",
            },
        ),
    ]
