# Generated by Django 5.0.2 on 2024-02-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': 'List Report'},
        ),
        migrations.AddField(
            model_name='user',
            name='nom_entreprise',
            field=models.CharField(default='entreprise', max_length=150, verbose_name='Nom Entreprise'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Email'),
        ),
    ]
