# Generated by Django 5.0.2 on 2024-05-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': 'Liste des  Rapport'},
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Upload rapport'),
        ),
    ]
