# Generated by Django 5.0.2 on 2024-02-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_report_options_user_nom_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Upload Report'),
        ),
    ]
