# Generated by Django 4.2 on 2025-01-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_reportfile_original_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fichier de Rapport', 'verbose_name_plural': 'Liste des Fichiers des Rapports'},
        ),
    ]
