# Generated by Django 5.0.2 on 2024-02-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=250)),
                ('numero_telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('etat', models.CharField(max_length=100)),
                ('pourquoi', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=250)),
                ('numero_telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('parametre_analyes', models.CharField(max_length=254)),
                ('type_debis', models.CharField(choices=[('1', 'Microbiologie'), ('2', 'Physicochimie')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('numero_telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cvfile', models.FileField(upload_to='uploads/')),
                ('transport', models.CharField(choices=[('1', 'Motorisé'), ('2', 'Non motorisé')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stagieur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('type_stage', models.CharField(choices=[('1', 'PFE'), ('2', 'PFA')], max_length=10)),
                ('numero_telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cvfile', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
