# Generated by Django 5.0.2 on 2024-05-06 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ParametersAnalyse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='nom et prénom')),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('numero_telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('etat', models.CharField(choices=[('satisfait', 'Satisfait'), ('non_satisfait', 'Non Satisfait')], default='satisfait', max_length=15, verbose_name='Etat du client')),
                ('pourquoi', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'List Avis Client',
            },
        ),
        migrations.CreateModel(
            name='Offre_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Nom du Post')),
                ('departement', models.CharField(max_length=100, verbose_name='département')),
                ('description', models.CharField(max_length=250)),
                ('temps', models.CharField(choices=[('1', 'Temps plein'), ('2', 'Partiel')], max_length=10)),
                ('contrat', models.CharField(choices=[('CIVP', 'CIVP'), ('CDI', 'CDI'), ('CDD', 'CDD'), ('Karama', 'Karama'), ('CSC', 'CSC')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "List d'offre d'emploi",
            },
        ),
        migrations.CreateModel(
            name='OffreStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Nom du Poste')),
                ('departement', models.CharField(max_length=100, verbose_name='département')),
                ('description', models.CharField(max_length=250)),
                ('type_stage', models.CharField(choices=[('1', 'PFE'), ('2', 'Stage Mémoire')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "List d'offre du stage",
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre Projet')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Multi Lab Projects',
            },
        ),
        migrations.CreateModel(
            name='Devi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100, verbose_name='nom et prénom')),
                ('nom_entreprise', models.CharField(blank=True, max_length=100)),
                ('poste', models.CharField(blank=True, max_length=250)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('parametre_analyes', models.CharField(blank=True, max_length=254)),
                ('type_debis', models.CharField(blank=True, choices=[('microbiologie', 'Microbiologie'), ('physicochimie', 'Physicochimie'), ('Alimentation_Animale', 'Alimentation Animale')], default='physicochimie', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_ALYSESPHYSICOCHIMIQUESPRODUITSPECHE', models.ManyToManyField(blank=True, related_name='devis_ALYSESPHYSICOCHIMIQUESPRODUITSPECHE', to='ParametersAnalyse.typedevianalysesphysicochimiquesproduitspeche')),
                ('type_ANALYSESPHYSICOCHIMIQUESHUILESETSGRAS', models.ManyToManyField(blank=True, related_name='devis_ANALYSESPHYSICOCHIMIQUESHUILESETSGRAS', to='ParametersAnalyse.typedevianalysesphysicochimiqueshuilesetproduitsgras')),
                ('type_ANALYSESPHYSICOCHIMIQUESMIEL', models.ManyToManyField(blank=True, related_name='devis_ANALYSESPHYSICOCHIMIQUESMIEL', to='ParametersAnalyse.typedevianalysesphysicochimiquesmiel')),
                ('type_ANALYSESPHYSICOCHIMIQUESVIANDESDERIVES', models.ManyToManyField(blank=True, related_name='devis_ANALYSESPHYSICOCHIMIQUESVIANDESDERIVES', to='ParametersAnalyse.typedevianalysesphysicochimiquesviandesderives')),
                ('type_Alimentation_Animale', models.ManyToManyField(blank=True, related_name='devis_Alimentation_Animale', to='ParametersAnalyse.typedevi')),
                ('type_AnalyseMicrobiologieProduitsEaux', models.ManyToManyField(blank=True, related_name='devis_AnalyseMicrobiologieProduitsEaux', to='ParametersAnalyse.typedevianalysemicrobiologieproduitseaux')),
                ('type_Analyses_Physicochimiques_Produits_Eaux', models.ManyToManyField(blank=True, related_name='devis_Analyses_Physicochimiques_Produits_Eaux', to='ParametersAnalyse.typeanalysesphysicochimiquesproduitseaux')),
                ('type_Analysesmicrobiologiquesproduitsalimentaires', models.ManyToManyField(blank=True, related_name='devis_Analysesmicrobiologiquesproduitsalimentaires', to='ParametersAnalyse.typedevianalysesmicrobiologiquesproduitsalimentaires')),
                ('type_BEURRE', models.ManyToManyField(blank=True, related_name='devis_BEURRE', to='ParametersAnalyse.typedevibeurre')),
                ('type_FROMAGE', models.ManyToManyField(blank=True, related_name='devis_FROMAGE', to='ParametersAnalyse.typedevifromage')),
                ('type_YSESPHYSICOCHIMIQUESPRODUITSLAITIERS', models.ManyToManyField(blank=True, related_name='devis_YSESPHYSICOCHIMIQUESPRODUITSLAITIERS', to='ParametersAnalyse.typedevianalysesphysicochimiquesproduitslaitiers')),
                ('type_azote_kjedahl', models.ManyToManyField(blank=True, related_name='devis_azote_kjedahl', to='ParametersAnalyse.typeazotekjedahl')),
            ],
            options={
                'verbose_name_plural': 'List Devis Client',
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='nom et prénom')),
                ('ville', models.CharField(max_length=100)),
                ('numero_telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cvfile', models.FileField(upload_to='uploads/', verbose_name='CV upload')),
                ('transport', models.CharField(choices=[('1', 'oui'), ('2', 'Non motorisé')], max_length=10, verbose_name='Motorisé?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre_emploi', to='multi_lab.offre_description')),
            ],
            options={
                'verbose_name_plural': 'List candidat',
            },
        ),
        migrations.CreateModel(
            name='Stagieur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Nom et prénom')),
                ('ville', models.CharField(max_length=100)),
                ('type_stage', models.CharField(choices=[('1', 'PFE'), ('2', 'PFA')], max_length=10)),
                ('numero_telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cvfile', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre_stage', to='multi_lab.offrestage')),
            ],
            options={
                'verbose_name_plural': 'List du stageurs ',
            },
        ),
    ]
