# Generated by Django 4.2 on 2025-01-27 08:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='nom et prénom')),
                ('nom_entreprise', models.CharField(max_length=100, verbose_name='Nom d entreprise')),
                ('numero_telephone', models.IntegerField(verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(max_length=254)),
                ('etat', models.CharField(choices=[('satisfait', 'Satisfait'), ('non_satisfait', 'Non Satisfait')], default='satisfait', max_length=15, verbose_name='FeedBack client')),
                ('pourquoi', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('pending', 'privé'), ('approved', 'Publié')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Liste Avis Client',
            },
        ),
        migrations.CreateModel(
            name='Candidate_simplify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('description', models.CharField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('file1', models.FileField(help_text='Upload PDF or ZIP file', upload_to='candidates/files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Simplified Candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_event', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('status', models.CharField(choices=[('published', 'Publié'), ('archived', 'Privé')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Multi Lab Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offre_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Nom du Post')),
                ('departement', models.CharField(max_length=100, verbose_name='Unité')),
                ('description', models.CharField(max_length=250)),
                ('temps', models.CharField(choices=[('1', 'Temps plein'), ('2', 'Partiel')], max_length=10, verbose_name='Type d emploi désiré')),
                ('contrat', models.CharField(choices=[('CIVP', 'CIVP'), ('CDI', 'CDI'), ('CDD', 'CDD'), ('Karama', 'Karama'), ('CSC', 'CSC')], max_length=10, verbose_name='Type d emploi désiré')),
                ('status', models.CharField(choices=[('pending', 'Privé'), ('approved', 'Publié')], default='pending', max_length=10, verbose_name='Status')),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "Liste d'offre d'emploi",
            },
        ),
        migrations.CreateModel(
            name='OffreStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Nom du Poste')),
                ('departement', models.CharField(max_length=100, verbose_name='Unité')),
                ('description', models.CharField(max_length=250)),
                ('type_stage', models.CharField(choices=[('1', 'PFE'), ('2', 'Stage Mémoire')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Privé'), ('approved', 'Publié')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "Liste d'offre du stage",
            },
        ),
        migrations.CreateModel(
            name='Persation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='persations/')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='persations/ ')),
                ('link_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('published', 'Publié'), ('archived', 'Privé')], default='archived', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'MULTILAB a.s Perstations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre Projet')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Privé'), ('approved', 'Publié')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Multi Lab Projects',
            },
        ),
        migrations.CreateModel(
            name='Stagieur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Nom et prénom')),
                ('ville', models.CharField(max_length=100)),
                ('type_stage', models.CharField(choices=[('1', 'PFE'), ('2', 'PFA')], max_length=10)),
                ('numero_telephone', models.IntegerField(verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(max_length=254)),
                ('cvfile', models.FileField(upload_to='uploads/', verbose_name='cv upload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre_stage', to='multi_lab.offrestage')),
            ],
            options={
                'verbose_name_plural': 'Liste des Stagiaires ',
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='nom et prénom')),
                ('ville', models.CharField(max_length=100)),
                ('numero_telephone', models.IntegerField(verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(max_length=254)),
                ('cvfile', models.FileField(upload_to='uploads/', verbose_name='CV upload')),
                ('transport', models.CharField(choices=[('1', 'oui'), ('2', 'Non motorisé')], max_length=10, verbose_name='Motorisé ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre_emploi', to='multi_lab.offre_description')),
            ],
            options={
                'verbose_name_plural': 'Liste candidate',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multi_lab.avis')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='event_articles/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='event_articles/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='event_articles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='multi_lab.event')),
            ],
        ),
    ]
