# Generated by Django 5.0.2 on 2024-02-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'verbose_name_plural': 'List Avis Client'},
        ),
        migrations.AlterModelOptions(
            name='devi',
            options={'verbose_name_plural': 'List Devis Client'},
        ),
        migrations.AlterModelOptions(
            name='offre',
            options={'verbose_name_plural': "List Offre d'emploi"},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Multi Lab Projects'},
        ),
        migrations.AlterModelOptions(
            name='stagieur',
            options={'verbose_name_plural': 'Offres du stage '},
        ),
    ]
