# Generated by Django 5.0.2 on 2024-05-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParametersAnalyse', '0001_initial'),
        ('multi_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devi',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='devi',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, verbose_name='nom et prénom'),
        ),
        migrations.AlterField(
            model_name='devi',
            name='nom_entreprise',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='devi',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='devi',
            name='poste',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='devi',
            name='type_ALYSESPHYSICOCHIMIQUESPRODUITSPECHE',
            field=models.ManyToManyField(blank=True, related_name='devis_ALYSESPHYSICOCHIMIQUESPRODUITSPECHE', to='ParametersAnalyse.typedevianalysesphysicochimiquesproduitspeche'),
        ),
        migrations.AlterField(
            model_name='devi',
            name='type_ANALYSESPHYSICOCHIMIQUESHUILESETSGRAS',
            field=models.ManyToManyField(blank=True, related_name='devis_ANALYSESPHYSICOCHIMIQUESHUILESETSGRAS', to='ParametersAnalyse.typedevianalysesphysicochimiqueshuilesetproduitsgras'),
        ),
        migrations.AlterField(
            model_name='devi',
            name='type_ANALYSESPHYSICOCHIMIQUESMIEL',
            field=models.ManyToManyField(blank=True, related_name='devis_ANALYSESPHYSICOCHIMIQUESMIEL', to='ParametersAnalyse.typedevianalysesphysicochimiquesmiel'),
        ),
        migrations.AlterField(
            model_name='devi',
            name='type_ANALYSESPHYSICOCHIMIQUESVIANDESDERIVES',
            field=models.ManyToManyField(blank=True, related_name='devis_ANALYSESPHYSICOCHIMIQUESVIANDESDERIVES', to='ParametersAnalyse.typedevianalysesphysicochimiquesviandesderives'),
        ),
        migrations.AlterField(
            model_name='devi',
            name='type_Alimentation_Animale',
            field=models.ManyToManyField(blank=True, related_name='devis_Alimentation_Animale', to='ParametersAnalyse.typedevi'),
        ),
        migrations.AlterField(
            model_name='devi',
            name='type_AnalyseMicrobiologieProduitsEaux',
            field=models.ManyToManyField(blank=True, related_name='devis_AnalyseMicrobiologieProduitsEaux', to='ParametersAnalyse.typedevianalysemicrobiologieproduitseaux'),
        ),
        migrations.AlterField(
            model_name='devi',
            name='type_Analyses_Physicochimiques_Produits_Eaux',
            field=models.ManyToManyField(blank=True, related_name='devis_Analyses_Physicochimiques_Produits_Eaux', to='ParametersAnalyse.typeanalysesphysicochimiquesproduitseaux'),
        ),
        migrations.AlterField(
            model_name='devi',
            name='type_Analysesmicrobiologiquesproduitsalimentaires',
            field=models.ManyToManyField(blank=True, related_name='devis_Analysesmicrobiologiquesproduitsalimentaires', to='ParametersAnalyse.typedevianalysesmicrobiologiquesproduitsalimentaires'),
        ),
        migrations.AlterField(
            model_name='devi',
            name='type_BEURRE',
            field=models.ManyToManyField(blank=True, related_name='devis_BEURRE', to='ParametersAnalyse.typedevibeurre'),
        ),
        migrations.AlterField(
            model_name='devi',
            name='type_FROMAGE',
            field=models.ManyToManyField(blank=True, related_name='devis_FROMAGE', to='ParametersAnalyse.typedevifromage'),
        ),
        migrations.AlterField(
            model_name='devi',
            name='type_YSESPHYSICOCHIMIQUESPRODUITSLAITIERS',
            field=models.ManyToManyField(blank=True, related_name='devis_YSESPHYSICOCHIMIQUESPRODUITSLAITIERS', to='ParametersAnalyse.typedevianalysesphysicochimiquesproduitslaitiers'),
        ),
        migrations.AlterField(
            model_name='devi',
            name='type_azote_kjedahl',
            field=models.ManyToManyField(blank=True, related_name='devis_azote_kjedahl', to='ParametersAnalyse.typeazotekjedahl'),
        ),
        migrations.AlterField(
            model_name='devi',
            name='type_debis',
            field=models.CharField(blank=True, choices=[('microbiologie', 'Microbiologie'), ('physicochimie', 'Physicochimie'), ('Alimentation_Animale', 'Alimentation Animale')], default='physicochimie', max_length=20),
        ),
    ]
