# Generated by Django 5.0.4 on 2025-01-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='persations/')),
                ('status', models.CharField(choices=[('published', 'Publié'), ('archived', 'Privé')], default='archived', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Multi Lab Persations',
                'ordering': ['-created_at'],
            },
        ),
    ]
