# Generated by Django 5.0.2 on 2024-05-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagieur',
            options={'verbose_name_plural': 'List des Stagiaires '},
        ),
    ]
