# Generated by Django 5.0.2 on 2024-02-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0002_alter_avis_options_alter_devi_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='nom et prénom'),
        ),
        migrations.AlterField(
            model_name='devi',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='nom et prénom'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='cvfile',
            field=models.FileField(upload_to='uploads/', verbose_name='CV upload'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='nom et prénom'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='transport',
            field=models.CharField(choices=[('1', 'oui'), ('2', 'Non motorisé')], max_length=10, verbose_name='Motorisé?'),
        ),
    ]
