# Generated by Django 5.0.4 on 2025-01-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0002_persation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offrestage',
            name='status',
            field=models.CharField(choices=[('pending', 'Privé'), ('approved', 'Publié')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Privé'), ('approved', 'Publié')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
