# Generated by Django 5.0.2 on 2024-05-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0002_alter_devi_email_alter_devi_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devi',
            name='parametre_analyes',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
