# Generated by Django 5.0.4 on 2025-01-06 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0003_alter_offrestage_status_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_event', models.DateTimeField()),
                ('image', models.ImageField(upload_to='events/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Multi Lab Events',
                'ordering': ['-date_event'],
            },
        ),
        migrations.CreateModel(
            name='EventArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='event_articles/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='event_articles/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='event_articles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='multi_lab.event')),
            ],
        ),
    ]
