# Generated by Django 5.0.2 on 2024-02-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0003_alter_avis_fullname_alter_devi_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Nom du Post')),
                ('departement', models.CharField(max_length=100, verbose_name='département')),
                ('description', models.CharField(max_length=250)),
                ('temps', models.CharField(choices=[('1', 'Temps plein'), ('2', 'Partiel')], max_length=10)),
                ('contrat', models.CharField(choices=[('CIVP', 'CIVP'), ('CDI', 'CDI'), ('CDD', 'CDD'), ('Karama', 'Karama'), ('CSC', 'CSC')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "List d'offre d'emploi",
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre Projet'),
        ),
    ]
