# Generated by Django 5.0.2 on 2024-02-28 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0004_offre_description_alter_project_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offre',
            options={'verbose_name_plural': 'List candidat'},
        ),
        migrations.AddField(
            model_name='offre',
            name='titre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offre_emploi', to='multi_lab.offre_description'),
        ),
    ]
