# Generated by Django 5.0.4 on 2025-01-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0004_event_eventarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('published', 'Publié'), ('archived', 'Privé')], default='draft', max_length=10),
        ),
    ]
