# Generated by Django 5.0.2 on 2024-02-28 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0005_alter_offre_options_offre_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='titre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre_emploi', to='multi_lab.offre_description'),
        ),
    ]
