# Generated by Django 5.0.4 on 2025-01-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0005_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
