# Generated by Django 5.0.2 on 2024-02-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0006_alter_offre_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Nom du Stage')),
                ('departement', models.CharField(max_length=100, verbose_name='département')),
                ('description', models.CharField(max_length=250)),
                ('type_stage', models.CharField(choices=[('1', 'PFE'), ('2', 'Stage Mémoire')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "List d'offre du stage",
            },
        ),
        migrations.AlterModelOptions(
            name='stagieur',
            options={'verbose_name_plural': 'List du stageurs '},
        ),
        migrations.AlterField(
            model_name='stagieur',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='Nom et prénom'),
        ),
        migrations.AddField(
            model_name='stagieur',
            name='titre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offre_stage', to='multi_lab.offrestage'),
        ),
    ]
