# Generated by Django 5.0.4 on 2025-01-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0006_alter_event_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Multi Lab Events'},
        ),
    ]
