# Generated by Django 5.0.2 on 2024-02-28 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0007_offrestage_alter_stagieur_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagieur',
            name='titre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre_stage', to='multi_lab.offrestage'),
        ),
    ]
