# Generated by Django 5.0.2 on 2024-03-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0008_alter_stagieur_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='offre_description',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='offrestage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
