# Generated by Django 5.0.4 on 2025-01-16 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_reportfile_original_name'),
        ('multi_lab', '0008_alter_persation_options_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.report'),
        ),
    ]
