# Generated by Django 5.0.4 on 2025-01-16 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0009_notification_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='avis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multi_lab.avis'),
        ),
    ]
