# Generated by Django 4.2 on 2025-01-20 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0010_alter_notification_avis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_simplify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('file1', models.FileField(help_text='Upload PDF or ZIP file', upload_to='candidates/files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Simplified Candidates',
                'ordering': ['-created_at'],
            },
        ),
    ]
