# Generated by Django 5.0.2 on 2024-03-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0010_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='etat',
        ),
        migrations.AlterField(
            model_name='avis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
