# Generated by Django 5.0.2 on 2024-03-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0011_remove_avis_etat_alter_avis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='etat',
            field=models.CharField(choices=[('satisfait', 'Satisfait'), ('non_satisfait', 'Non Satisfait')], default='satisfait', max_length=15, verbose_name='Etat du client'),
        ),
    ]
