# Generated by Django 4.2 on 2025-01-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0011_candidate_simplify'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_simplify',
            name='description',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
