# Generated by Django 5.0.2 on 2024-03-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0012_avis_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='message',
        ),
    ]
