# Generated by Django 5.0.2 on 2024-03-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0013_remove_avis_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devi',
            name='type_debis',
            field=models.CharField(choices=[('microbiologie', 'Microbiologie'), ('physicochimie', 'Physicochimie')], default='physicochimie', max_length=20),
        ),
    ]
