# Generated by Django 5.0.2 on 2024-04-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0014_alter_devi_type_debis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devi',
            name='numero_telephone',
            field=models.IntegerField(verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='offrestage',
            name='titre',
            field=models.CharField(max_length=100, verbose_name='Nom du Poste'),
        ),
    ]
