# Generated by Django 5.0.2 on 2024-04-02 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0015_alter_devi_numero_telephone_alter_offrestage_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagieur',
            name='titre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offre_stage', to='multi_lab.offrestage'),
        ),
    ]
