# Generated by Django 5.0.2 on 2024-04-02 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0016_alter_stagieur_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre_description',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagieur',
            name='titre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre_stage', to='multi_lab.offrestage'),
        ),
    ]
