# Generated by Django 5.0.2 on 2024-04-30 08:01

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0017_offre_description_experience_alter_stagieur_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devi',
            name='type_debis',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
