# Generated by Django 5.0.2 on 2024-04-30 08:06

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_lab', '0018_alter_devi_type_debis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devi',
            name='type_debis',
            field=models.CharField(choices=[('microbiologie', 'Microbiologie'), ('physicochimie', 'Physicochimie'), ('Alimentation_Animale', 'Alimentation Animale')], max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
