# Generated by Django 5.0.2 on 2024-02-17 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=250)),
                ('numero_telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('etat', models.CharField(max_length=100)),
                ('pourquoi', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('numero_telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=250)),
                ('numero_telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('parametre_analyes', models.CharField(max_length=254)),
                ('type_debis', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('numero_telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cvfile', models.FileField(upload_to='uploads/')),
                ('transport', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stagieur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('type_stage', models.CharField(max_length=100)),
                ('numero_telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cvfile', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='multi_lab.clients')),
            ],
        ),
    ]
